apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service-deployment
  namespace: library-service-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-service
  template:
    metadata:
      labels:
        app: library-service
    spec:
      containers:
        - name: library-service-container
          image: library-service-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8100
